name: Trivy Scan
on:
  workflow_call:
    inputs:
      repo-name:
        description: 'Name of the repository'
        required: false
        type: string

env:
    SCAN_SEVERITY: 'CRITICAL,HIGH,MEDIUM'
    SCAN_FORMAT: 'table'
    SCAN_OUTPUT: 'trivy-results.txt'

jobs:
    trivy-scan:
        runs-on: ubuntu-latest
        continue-on-error: true
        permissions:
            contents: read
            security-events: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'config'
                scan-ref: '.'
                severity: ${{ env.SCAN_SEVERITY }}
                format: ${{ env.SCAN_FORMAT }}
                output: ${{ env.SCAN_OUTPUT }}
                cache: 'false'
            
            - run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            - name: Create Issue From File
              uses: peter-evans/create-issue-from-file@v6
              with:
                title: Trivy Scan Results on ${{ env.CURRENT_DATE }}
                content-filepath: ${{ env.SCAN_OUTPUT }}
                labels: |
                  trivy-scan

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v4
              if: always()
              with:
                sarif_file: ${{ env.SCAN_OUTPUT }}
